### ISSUE TITLE
No easy way to disconnect slaves safely

### ISSUE THREAD

**Issue by drobertduke** [box/ClusterRunner#117]
To disconnect a slave, I need to check if it is running a build first.  If it receives a build between my check and my disconnect request, the build will fail (is that correct?).

I'd like an endpoint on the master that would take a list of slave ids and disconnect them once safely (waiting until each one is idle).

**Comment by josephharrington** [comment]
:+1:

**Comment by josephharrington** [comment]
Completed by #118.
