### ISSUE TITLE
Docs link to localhost

### ISSUE THREAD

**Issue by guykisel** [box/ClusterRunner#124]
On http://www.clusterrunner.com/docs/build-result-format/ the link embedded in "If you're using a CI tool to process your build results, it's unlikely you'll need to interact with these build results manually." goes to `http://localhost:4000/docs/ci-integration/#publish-build-results-in-ci`.

**Comment by guykisel** [comment]
Looks like the problem is in https://raw.githubusercontent.com/box/ClusterRunner/gh-pages/_docs/build-result-format.md

**Comment by josephharrington** [comment]
Fixed! Thanks!!
