### ISSUE TITLE
Many idle clusterrunner processes on master

### ISSUE THREAD

**Issue by tjlee0909** [box/ClusterRunner#127]
When performing a 'ps aux | grep clusterrunner' on the master, you see results such as this:

jenkins   3009  0.0  1.2 2338040 960624 ?      Sl   Apr13   0:00 /home/jenkins/.clusterrunner/dist/clusterrunner master --port 43000
jenkins   3825  0.0  1.1 2128648 835540 ?      Sl   Apr13   0:00 /home/jenkins/.clusterrunner/dist/clusterrunner master --port 43000
jenkins   4380  0.0  2.0 2749068 1511444 ?     Sl   Apr16   0:00 /home/jenkins/.clusterrunner/dist/clusterrunner master --port 43000
jenkins   6512  0.0  0.8 1983204 617116 ?      Sl   Apr10   0:00 /home/jenkins/.clusterrunner/dist/clusterrunner master --port 43000
jenkins   6959  0.0  0.3 1797332 257012 ?      Sl   Apr09   0:00 
...

From PaulSouthworth:
sudo strace -p 29768
Process 29768 attached - interrupt to quit
futex(0x1033610, FUTEX_WAIT_PRIVATE, 0, NULL
-- that looks like waiting forever

This ticket is to figure out why these processes continue proliferating, even though they are idle, and get rid of it.

**Comment by tjlee0909** [comment]
David Duke suggested:  http://stackoverflow.com/questions/10115126/python-requests-close-http-connection
============
10:54 s = requests.session()
s.config['keep_alive'] = False

**Comment by tjlee0909** [comment]
Potentially fixed by https://github.com/box/ClusterRunner/pull/168

**Comment by josephharrington** [comment]
Aw yeah, definitely fixed by #168.
