### ISSUE TITLE
Flaky test `test_shutting_down_after_running_a_build_does_not_raise_exception`

### ISSUE THREAD

**Issue by aptxkid** [box/ClusterRunner#169]
`test_shutting_down_after_running_a_build_does_not_raise_exception` is flaky and I can reproduce the failure by decorating the test with `genty_repeat` locally.

**Comment by josephharrington** [comment]
Hey Lu, can you add the failure output to this issue?

**Comment by aptxkid** [comment]
@josephharrington That's the same failure I saw. Yay for testing!

**Comment by aptxkid** [comment]
@josephharrington I think it's more a problem of the test than a real race condition in production. Here's what I found.

`slave.setup_build` is actually async as well and it will set `teardown_done_event` as well. So if the real `slave.teardown_build` is slow (because it's async as well), `self.assertTrue(teardown_done_event.wait()` will pass while `_do_build_teardown_and_reset` has not be executed even once. And now `MainThread` is calling `trigger_graceful_app_shutdown`. Remember `slave.teardown_build` is slow? Now both the teardown thread and mainthread can be in the `_do_build_teardown_and_reset` method at the same time. And it can fail the test if both pass the `if not self._project_type:` check. If we wait `slave.setup_build` to finish before all the rest should solve the problem.

* debugging this race condition with so many async calls and callbacks was fun :smile:

**Comment by josephharrington** [comment]
Slow clap... :clap:... :clap:... :clap:...
