### ISSUE TITLE
Output which slave ran/is running a particular subjob

### ISSUE THREAD

**Issue by tjlee0909** [box/ClusterRunner#235]
We thought it'd be a good idea to abstract away the specific hosts that are running subjobs, but in reality, things go wrong with individual machines that require debugging.

Right now, in order to figure out which machine ran which subjob, it requires some digging into logs in multiple places, and is generally very difficult to do.

I suggest we add the slave hostname to the v1/build/<id>/subjob/<id> endpoint.

**Comment by josephharrington** [comment]
Is this different than #230?

**Comment by tjlee0909** [comment]
Duplicate
