### ISSUE TITLE
Implement a session token for ClusterRunner

### ISSUE THREAD

**Issue by tjlee0909** [box/ClusterRunner#245]
ClusterRunner currently retains no state in between service restarts. All first builds after a restart starts with build id 1.

This becomes problematic when integrating ClusterRunner with a different service that persists state forever. We need the concept of a session token, that is unique per service restart, that would be used to authenticate requests and make sure that the requests are for the correct builds.

**Comment by josephharrington** [comment]
+1
It would be nice if specifying the session token in API requests was optional. If I want to pull up the api response for a specific build, I shouldn't *need* to go figure out the current session id. 

I was also thinking that http if-match and etag headers might be appropriate for this.

**Comment by tjlee0909** [comment]
Agreed about making it optional, meaning that if someone doesn't specify the session ID, it means they don't care about whether or not they might be looking at the wrong session.

I'm wondering how we will return the session ID. Should it be returned with the build id in the POST build requests?

I'm thinking that all GETS that do provide the session ID, and the session ID is not the same, then we will return a 40X code.

I'm not quite sure what we want to do for POSTS regarding session ID's.

I don't know what an etag header is, I'll look it up.

**Comment by josephharrington** [comment]
The downside of a header is that it wouldn't be completely contained within the url. That might be a dealbreaker.
