### ISSUE TITLE
Integration with Behat

### ISSUE THREAD

**Issue by geraldvillorente** [box/ClusterRunner#270]
Is it possible to integrate Behat testing with ClusterRunner?

**Comment by josephharrington** [comment]
Hey @geraldvillorente -- ClusterRunner is generally agnostic to the testing framework so you could probably use it to run behat tests as long as behat allows you to execute tests on single files. The file-level execution is usually desirable for ClusterRunner's atomization to be most effective.

Check out the [demo project's clusterrunner.yaml](https://github.com/boxengservices/ClusterRunnerDemo/blob/master/clusterrunner.yaml#L18-L31) for a more concrete example of how to use various testing frameworks.

**Comment by geraldvillorente** [comment]
@josephharrington thank you it is working as expected. /rocks

**Comment by geraldvillorente** [comment]
So this is what I did
```
atomizers:
        - TESTPATH: find "features" -name "*.feature"
```

**Comment by josephharrington** [comment]
Great! Let us know if you run into any other issues. :)
