### ISSUE TITLE
Better handle when a host requests to connect to the master again (with the same port)

### ISSUE THREAD

**Issue by tjlee0909** [box/ClusterRunner#293]
If slave1.pod.box.net is running on port 43001 and is already connected to the master, and the same slave requests to connect to the master on the same port again, we should probably reject the connection request.

Last night, we had this happen (the reason for having the same slave request to connect again is user error, but regardless the ClusterMaster should handle this better). slave1 was working on build100, and then the slave1 requested to connect again to the master, and the master happily obliged, and sent that new instance of slave1 a subjob for build101, which led to a fatal error.

**Comment by josephharrington** [comment]
This is fixed since the master now keeps track of a session id for each slave. If a slave is started up on the same host and port, the newer instance will overwrite the older one and any API requests meant for the old slave will fail on the new one because the session id won't match.
