### ISSUE TITLE
ClusterRunner binary management in Github repo

### ISSUE THREAD

**Issue by tjlee0909** [box/ClusterRunner#295]
@asheepapart suggested that we stop using Box to host our ClusterRunner binaries, and instead perhaps host them inside the CR repo itself, or in a separate binary repo we create in github.

If we do this, I think it's a good excuse to implement some automation that includes the release number, as well as perhaps a little summary (could even just be the git commit titles for patches in the new build) for that build.

This is related to https://github.com/box/ClusterRunner/issues/285

**Comment by josephharrington** [comment]
+1 to hosting using github releases if possible. https://developer.github.com/v3/repos/releases/#upload-a-release-asset

**Comment by asheepapart** [comment]
:+1: :cloud:

**Comment by tjlee0909** [comment]
Done.
