### ISSUE TITLE
Reconnecting a slave can take down the master

### ISSUE THREAD

**Issue by josephharrington** [box/ClusterRunner#296]
This occurs when an idle slave is hard killed (SIGKILL / kill -9) and then reconnected. (As opposed to a graceful kill with SIGTERM / kill -15.) Local reproduction steps are below.

I believe the cause is that when we connect a slave, we detect if it's a "reconnect" meaning a slave with the same host name and port has been connected before. We do some work to clean up the old slave instance but it is incomplete. 

We remove the slave from `self._all_slaves_by_url` but if it is idle, that instance is still in the SlaveAllocator's idle slaves queue so it can still be assigned to a build. We should probably just call `self._disconnect_slave()` and let that method handle cleaning up the old slave.

Reproduction steps:

```bash
./main.py master &
./main.py slave  --num-executors 5 &
kill -9 `cat ~/.clusterrunner/.clusterrunner_slave.pid`
./main.py slave  --num-executors 5 &

# At this point you'll see the "Removing existing slave instance from the master's bookkeeping." log message.

# Now start two concurrent builds...
./main.py build directory --project-directory examples/directory\ job/ & 
./main.py build directory --project-directory examples/directory\ job/ &

# At this point the master will die with "Attempted to start subjob 0 for build 1, but current build id is 2."
# The slave will keep running. Both build commands will eventually time out since they can't contact the master.
```

**Comment by tjlee0909** [comment]
Nice debugging work there.

**Comment by josephharrington** [comment]
Just for a bit more background, there's a line in the SlaveAllocator where we discard slaves from the idle slave queue:
```python
                # Remove dead and shutdown slaves from the idle queue
                if claimed_slave.is_shutdown() or not claimed_slave.is_alive(use_cached=False):
                    continue
```

The semantics around `slave.is_alive()` are a bit weird to me -- I don't think consuming code should need to care about when it's using a cached value vs. a non-cached value since most of the time that decision requires more context than consuming code should care about.

I was thinking of refactoring that to something like `slave.can_accept_builds()` and then the slave could internally take care of deciding whether to use cached values or not. Just a thought -- it might make it easier to handle the case when a slave is reconnected.

Another angle I was thinking about for this was to have the slave generate a unique session id when it connects, and then the master sticks that unique id in a header whenever it sends a request to the slave. The slave could return some error response (e.g., http 412) if the unique id does not match and otherwise ignore the request. Doing this should solve the problem of the `slave.is_alive()` check in SlaveAllocator returning true even if the slave has been reconnected (the master is talking to a new slave instance but thinks it is the old one).

**Comment by tjlee0909** [comment]
I'm down with the unique session ID per slave idea.

High level, it looks like the pull requests would break out into roughly these changes:

1). Slave generates a unique session ID upon service startup, and sends it to the master in the payload when connecting to the master.

2). Master parses this session ID (if specified) and stores it in its internal Slave instance. All network calls from the master to slave start having this ID (if originally specified by the slave) in the header.

3). Master must be able to handle all exceptional cases during network calls to the Slaves where the session ID is incorrect, leading to a 403 response.

4). Slave service will start rejecting all network calls that have specified an incorrect session id.

------------------------

Question:

Should we make this session id an optional? Meaning, if the master doesn't specify the session ID in the header in a request to the slave, should we just allow it to go through? My inclination is to say yes, as the only reason why we have this session ID in the first place is to make sure the master knows which session the slave is; if the master doesn't specify the session ID in the header, then it should signal that the master doesn't care which session the slave is on for that particular request.

**Comment by josephharrington** [comment]
Sounds good. And yeah, agreed -- I was also thinking we'd just make the session id optional.
