### ISSUE TITLE
Linux tgz release files contain MIME headers

### ISSUE THREAD

**Issue by Jawshua** [box/ClusterRunner#316]
When downloading the `clusterrunner-linux.tgz` file, it cannot be uncompressed due to the header of the file containing MIME data before the gzip payload

For example, the header of https://github.com/box/ClusterRunner/releases/download/0.5.461/clusterrunner-linux.tgz is
```
--08381939667b4228ab04cc54b6bd7378
Content-Disposition: form-data; name="file"; filename="clusterrunner-linux.tgz"
Content-Type: application/gzip
```

Tested using Chrome, wget, and curl.

**Comment by josephharrington** [comment]
Thanks for letting us know, @Jawshua. We'll look into what's wrong with our binaries on GitHub releases.

For now, you should be able to use the binary [linked from the docs](http://www.clusterrunner.com/docs/installation/). I just verified this works for me:
```
[🍺 🍺 🍺  ~/cr_test]▸ curl -L https://cloud.box.com/shared/static/2pl4pi6ykvrbb9d06t4m.tgz > clusterrunner-linux.tgz
[🍺 🍺 🍺  ~/cr_test]▸ mkdir dist
[🍺 🍺 🍺  ~/cr_test]▸ tar -zxvf clusterrunner-linux.tgz -C ./dist
[🍺 🍺 🍺  ~/cr_test]▸ ./dist/clusterrunner --version
ClusterRunner 0.5.461
```

**Comment by josephharrington** [comment]
There was a bug in our script to upload binaries to GitHub releases. That has now been fixed so the most recent and future binaries should be good to go. Thanks, @Jawshua!
