### ISSUE TITLE
Set pipefail option in shell environment

### ISSUE THREAD

**Issue by josephharrington** [box/ClusterRunner#321]
This is a suggestion from @pwsouth to make the results of shell executions less surprising.
https://sipb.mit.edu/doc/safe-shell/

I'm not sure what the equivalent is for windows.

**Comment by josephharrington** [comment]
This came up again in an `sbt` command inside an atomizer command. The `sbt` command ran out of memory but since the output was piped to `awk`, it appeared that the atomizer command succeeded (with zero atoms). Thus the build succeeded even though no tests were run.

**Comment by josephharrington** [comment]
Quick demo of the issue and how setting the pipefail option fixes it:
```bash
$> (echo hello; exit 1) | grep h
hello
$> echo $?
0

$> set -o pipefail
$> (echo hello; exit 1) | grep h
hello
$> echo $?
1
```

**Comment by cmcginty** [comment]
https://jira.inside-box.net/browse/PE-12928
