### ISSUE TITLE
Url with missing scheme can create ambiguous clone directories

### ISSUE THREAD

**Issue by josephharrington** [box/ClusterRunner#324]
When the master gets a git-type build request with a url that looks something like `ssh://scm.dev.box.net:12345/awesome-project`, it clones it to the directory `~/.clusterrunner/repos/master/scm.dev.box.net12345/awesome-project/`. That's correct and unambiguous across hosts.

However if we get something like `git.dev.box.net:Productivity/ClusterRunnerHealthCheck`, the clone directory will be `~/.clusterrunner/repos/master/Productivity/ClusterRunnerHealthCheck/` which does not include the hostname, so will be ambiguous across hosts and can lead to unpredictable behavior.

For example, if we send a build request for a different host with the same repo name ("Productivity/ClusterRunnerHealthCheck") the clusterrunner master will reuse a repo clone that has its remotes pointed at a different host.

This is an issue with the `_generate_path_from_repo_url` method in app/project_type/git.py, and ultimately an unexpected behavior of stdlib `urllib.parse.urlparse`:

```python
urlparse('git.dev.box.net:Productivity/ClusterRunnerHealthCheck')
# ParseResult(scheme='git.dev.box.net', netloc='', path='Productivity/ClusterRunnerHealthCheck', params='', query='', fragment='')
```
Note above that the `scheme` field, not the `netloc` field, contains the hostname, which is surprising.

Also note that the clone itself *does* work with that url, so instead of requiring a scheme on urls we probably just need to be smarter in dealing with various input formats.

**Comment by nickzuber** [comment]
@josephharrington  Is the goal here with `_generate_path_from_repo_url` to just generate a deterministic path for a repository url or is there some type of convention we want to stick with? Like is there a particular reason we don't want to include a scheme _and_ netloc when generating the url?

Also what other input formats should we expect besides the two mentioned here?

**Comment by josephharrington** [comment]
@nickzuber I don't think the convention is too important as long as it's unique. That said, I don't love including scheme as the *only* fix for this issue -- it is surprising that the input url is not parsed correctly and could lead to other bugs in the future if someone changes this code and expects it to act sane.

Another consideration is that we probably don't want to change the generated path for most repos if we can help it. If the path changes then that will cause repos to be recloned the next time clusterrunner is upgraded which depending on the repo can be undesirable.

@tjlee0909 @nadeemahmad  Do you know if we still do prepopulation of repos on our slave images? If so, then we'd want to be extra careful with this change to make sure CR is still looking for those repos in the right place.

Maybe something like this would work:
- Check if `netloc` is empty
- If not empty, assume good and use existing logic.
- If empty, go ahead and include the scheme in the generated path (along with a comment in the code that the url is malformed).

**Comment by tjlee0909** [comment]
I'd assume we are still running the pre-populate repos provisioner when creating CR slave images in packer.

**Comment by nickzuber** [comment]
Are there any other possible url inputs we could get that'd also have this unexpected behavior that we know about? Like will the logic of using `scheme` whenever `netlock` is empty always work?

**Comment by josephharrington** [comment]
> Are there any other possible url inputs we could get that'd also have this unexpected behavior that we know about? Like will the logic of using scheme whenever netloc is empty always work?

Good question. Since the url value is user input it might be worth investigating. Basically if git can successfully clone from a certain url then our logic should be able to handle that url. 

(As a side note, I see in the original issue that I said git *could* handle the url `git.dev.box.net:Productivity/ClusterRunnerHealthCheck` but now when I try that same url I get an error. I'm not sure what was different back when I originally wrote this up, but even so, I think it's still worth fixing.)


> Also should we write some unit tests for _generate_path_from_repo_url when we're fixing this? I don't think we currently have any.

Definitely. I think there is at least one test right now (tested via public interface of `Git.get_full_repo_directory(url)` but obviously there should be more tests.

**Comment by nickzuber** [comment]
What do we do currently if someone gives bad input for a repo url? Does something else handle it or is handling that within the scope of `Git.get_full_repo_directory`?

**Comment by tjlee0909** [comment]
@nickzuber - you could probably just test that out locally, and see what happens.

**Comment by nickzuber** [comment]
@tjlee0909 Yeah so it looks like we throw an error when we can't clone a repo with a bad url which makes sense. So this means its safe for `Git.get_full_repo_directory` to assume it has a real & valid url. 

I also notice in `_generate_path_from_repo_url` we remove the colons from the `netloc` -- how come? I ask because we don't remove colons from `path`, which makes something like

```
urlparse('git@git.dev.box.net:Productivity/ClusterRunnerHealthCheck.git')
# ParseResult(scheme='', netloc='', path='git@git.dev.box.net:Productivity/ClusterRunnerHealthCheck.git', params='', query='', fragment='')
```

create a repo directory like 
```
~/.clusterrunner/repos/master/git@git.dev.box.net:Productivity/ClusterRunnerHealthCheck
```` 
(which I currently have on my computer) -- is this intended?

**Comment by josephharrington** [comment]
I think that colons are not supported in filenames/paths in Windows. If they're not being removed then that is surprising and probably a bug.

**Comment by nickzuber** [comment]
@josephharrington It seems like the colon is replaced with a slash in Finder but when looking at the directory in my terminal, it has the colon. Either way the function we currently have for generating a repo directory is returning a path with a colon so we should fix it.
