### ISSUE TITLE
ClusterRunner output should show relative test path on it's own line

### ISSUE THREAD

**Issue by pwsouth** [box/ClusterRunner#330]
This issue was originally filed as PE-12180 by Richard Pon. Original problem report:

One of the use cases with the ClusterRunner output is to reproduce a failed test run on my DEV VM. The ClusterRunner console output contains all the information needed to do so, but is slightly cumbersome

The atoms are labeled like
export TESTPATH="$PROJECT_DIR/test/php/integration/modular/ravioli-mdmInstance/mdmInstance-impl/src/main/MDMInstanceCreateOpTest.php";

I really just want to copy the relative test path so I can paste it into a terminal to run the test. So in the above string, all I want is

test/php/integration/modular/ravioli-mdmInstance/mdmInstance-impl/src/main/MDMInstanceCreateOpTest.php

Right now, I have to slowly and carefully select the relative test path to copy. It's not too much of a pain, but kinda sucks considering it's a repetitive task I have to do hundreds of times.

**Comment by josephharrington** [comment]
After thinking about this, I'm actually going to move this to an issue on the repo for our (internal) streaming console output UI.
