### ISSUE TITLE
Build result zips sometimes contain a different build's results

### ISSUE THREAD

**Issue by josephharrington** [box/ClusterRunner#383]
Sometimes the artifacts.zip for a build will be completely incorrect, containing the results of a entirely different build.

Since console output logs for completed subjobs are pulled from this zip archive, sometimes the API will also return console output for a different build. Depending on what a build outputs this can be very hard to detect. Often the only sign something is wrong is that an atom is recorded as failing but the console output looks successful.

The root cause of this is a race condition in Python's `shutil.make_archive`. That method is actually not at all thread-safe, even though that caveat is undocumented. There is [an issue](https://bugs.python.org/issue30511) filed against Python related to this.

We should be able to work around this by using the `zipfile` module directly instead of going through `shutil`.

**Comment by wjdhollow** [comment]
This is user facing. I think we should prioritize this work. A user only recognized this bug because it said the wrong test failed. This may possibly be affecting more users, but unnoticed due to no test failures.

**Comment by josephharrington** [comment]
Agreed. Prioritized. Just to clarify though, it only affects the console output for atoms -- builds overall success/fail status and record of which atoms failed is still correct.

**Comment by josephharrington** [comment]
Also, the tar archive (artifacts.tar.gz) will still contain the correct results, so if a user really needs to see console output for a failed atom then they have the option of downloading the tar archive.
