### ISSUE TITLE
Pagination Proposal

### ISSUE THREAD

**Issue by nickzuber** [box/ClusterRunner#393]
The first part that we need to figure out for pagination is how to get the requested range of results. This depends on how we want to paginate -- by actual pages or just limiting results.

We can do this with query parameters `start` and `amount`, or alternatively `page` and `per_page`. If we go through the route of having actual pages then we'd want a way to show `next` and `prev` pages probably just through some field in the response. 

If we went with the `start` and `amount` approach, we could provide an HTTP handler method with a decorator to introduce the respective `start` and `amount` values.

```python
DEFAULT_PAGINATION_START = 0
DEFAULT_PAGINATION_AMOUNT = 50

def paginated(func):
    def function_with_pagination(self, *args, **kwargs):
        start = int(self.get_query_argument('start', DEFAULT_PAGINATION_START, True))
        amount = int(self.get_query_argument('amount', DEFAULT_PAGINATION_AMOUNT, True))
        pagination_range = { 'start': start, 'amount': amount }
        return func(self, *args, pagination_range=pagination_range, **kwargs)

    return function_with_pagination
```

Then we could use this like

```python
@paginated
def get(self, pagination_range):
    start, amount = pagination_range.values()
    response = {
        'builds': [build.api_representation() for build in self._cluster_master.builds(start, amount)]
    }
    self.write(response)
```

And for example, to limit the builds we could do

```python
def builds(self, start=None, amount=None):
    """
    Returns a list of all builds
    :rtype: list[Build]
    """
    num_builds = len(self._all_builds_by_id)
    start = start or 0
    amount = amount or num_builds
    return [self._all_builds_by_id[key] for key in islice(self._all_builds_by_id, start, min((start + amount), num_builds))]
```

**Comment by ethomas2** [comment]
I like the `start` and `amount` way you suggested. 

I don't understand the other suggestion. The "actual pages" way where there are `prev` and `next`. Can you expand on that? Ie what would this look like to the user, and what will implementation look like.

**Comment by nickzuber** [comment]
@ethomas2 Yeah so an example of this is github's API. I think they do things a bit differently but the idea is that you split the results into pages with x amount per page. 

So you could have something like `builds?per_page=10&page=1` and the response could maybe some additional field linking to the next and previous pages. This could give you something like

```javascript
{
    "child_routes": { 
        // ...
    },
    "builds": {
        // ...
    },
    "navigation": {
        "prev": null,
        "next": "builds?per_page=10&page=2"
    }
}
```

Just a different style if we wanted to do something like that, but I also like the idea of having `start` and `amount` for our use case

**Comment by josephharrington** [comment]
- I also like the start/amount approach over page numbers. I think we should have the prev and next links no matter which we choose. Is "start" and "amount" a standard anywhere? I was wondering if "offset" and "limit" might be more common.

- What do you think of having a fixed maximum to the "amount" parameter? Part of the reason for adding pagination is to protect against responding with huge payloads containing thousands of results, so I think it would be reasonable to set a hard limit on how much we return.

- This might be unnecessary what do you think about also supporting negative "start" values to count backwards from the end (similar to Python's negative list indexing)? That would allow us for example to get the *last* 10 builds which would be useful.

- I like the look of decorators in general, so it hurts me a little to say this, but I think in this case a decorator might be overkill. For example, the code snippet you wrote:
    ```python
    @paginated
    def get(self, pagination_range):
        start, amount = pagination_range.values()
        ...
    ```
    might be simpler as:
    ```python
    def get(self):
        start, amount = self._get_pagination_params()
        ...
    ```
    especially because then there is not any overloading of the parameters to `get()`. Right now parameters to `get()` only come from one source (the matching groups in the route regex) so it might be preferable not to complicate that.

- I like that your examples are passing the pagination parameters in to the `builds()` method itself instead of getting the entire list in the web layer and truncating it there. That would make it easier in the future if we changed things to be backed by a database (so wanted to only query for the requested range).

**Comment by nickzuber** [comment]
@josephharrington 

> Is "start" and "amount" a standard anywhere? I was wondering if "offset" and "limit" might be more common.

The examples I found used `page` and `per_page` so I'm not sure if there's some kind of convention with other types of naming. I'll keep looking around but if there doesn't seem to be a standard we should just go with whatever makes the most sense.

> What do you think of having a fixed maximum to the "amount" parameter?

Sure that sounds like it'd be a good idea.

> This might be unnecessary what do you think about also supporting negative "start" values to count backwards from the end (similar to Python's negative list indexing)?

That seems like it'd be pretty straightforward to implement, so if this is something that we'd use and want to support then I think we should. But if we won't or don't plan on using it then we probably don't want to overcomplicate things too much. 

> I like the look of decorators in general, so it hurts me a little to say this, but I think in this case a decorator might be overkill.

Ah yeah I like the private method approach much better -- I didn't like adding parameters to the http methods for that exact reason, so this would be much cleaner. 

> I like that your examples are passing the pagination parameters in to the builds() method itself instead of getting the entire list in the web layer and truncating it there.

🎉  It also helps abstract pagination to be more accessible for other http methods that might implement things differently too.

**Comment by nickzuber** [comment]
Also what do we want to do about default limits? I remember that we want to paginate by default, so what should that default be?

**Comment by josephharrington** [comment]
How about a default of 20, max of 200? I just loaded the build endpoint on our production master and it gave me 1430 builds with a 6.5mb response. I think shooting for a max response size of around 1mb is a good guideline.
