### ISSUE TITLE
Build cancellation is broken

### ISSUE THREAD

**Issue by josephharrington** [box/ClusterRunner#396]
This is closely related to #224, but I wanted to capture some of the more general issues with cancellation as it's currently implemented.

Build cancellation has never worked well, and is completely broken right now. The [one functional test](https://github.com/box/ClusterRunner/blob/master@{2017-07-28}/test/functional/master/test_endpoints.py#L33) we have for cancellation really only tests the API response, not the actual cancellation behavior.

A few of the major issues:
- Canceling a build before clone/atomization doesn't prevent clone/atomization.
- Canceling during clone/atomization doesn't stop clone/atomization.
- Canceling any time before atomization is finished will put the build in an `ERROR` state. It will also still run the entire build; the cancellation basically has no effect except to put the build into an `ERROR` state.
- Canceling a build while it's building is the worst one. The behavior here is essentially what was listed originally in #224 for queued builds: all slaves working on the build will be stuck forever waiting for more subjobs.

### Background: What happens when a build is canceled?
- The current implementation of canceling a build is simple:
	1. Transition the BuildFsm state to `CANCELED` (which can cause errors later on.)
	2. Clear out the build's `_unstarted_subjobs` queue.
- Code flow: `build.cancel()` -> [`build._on_enter_canceled_state()`](https://github.com/box/ClusterRunner/blob/master@{2017-07-28}/app/master/build.py#L326-L331)
- Due to the BuildFsm, a build will only enter `CANCELED` state once. So even if `build.cancel()` is called multiple times, the `_unstarted_subjobs` queue will only be cleared once.
- A large source of problems is the design choice to clear the `_unstarted_subjobs` queue. This is error-prone and should not be necessary since we can just check if the state of the build is `CANCELED` or not.
    - **This implementation detail is why canceling a build while it's being atomized does not work.** At that point there are no subjobs yet, so clearing the `_unstarted_subjobs` queue is a no-op. It's only once atomization finishes that the queue is populated.

### What we want
There are two effects "canceling a build" should have:
1. Don't start any new work.
2. Immediately stop any in-progress work.

(1) is more important than (2). The current implementation of build cancellation is a buggy attempt at doing (1), and does not make any attempt to do (2). I think we should start by fixing all issues with (1), and only then move on to (2).

### Potentially long-running phases in which a build could be canceled
- Queued (waiting to clone/atomize)
	- `BuildRequestHandler._prepare_build_async()`
	- Build is waiting for project lock while other builds from same repo are being atomized

- Cloning (prereq to atomization)
	- `build.prepare()` -> `self.project_type.fetch_project()`
	- Build's repo is being cloned

- Atomizing
	- `subjob_calculator.compute_subjobs_for_build()`
	- Build's atomizer command is being executed inside the repo clone
	- In ClusterMaster there is a line: `if not build.is_finished or build.has_error:`
		- Any time we skip executing the logic inside this if-block, slaves will get stuck. :(
		- Confusingly, `build.is_finished` in this context will only return True if the build has been canceled.
		- I think this line originally was the source of #224, but that issue description is outdated since the addition of the BuildFsm. (Although those negative effects do still occur if a build is canceled while building.) 

- Waiting for slaves
	- `BuildSchedulerPool._builds_waiting_for_slaves`
	- build is in line to be assigned slaves, may stay here a long time during busy hours

- Being assigned slaves
	- `SlaveAllocator._slave_allocation_loop()`
	- Build has at least one slave working on it but is waiting on more slaves to be assigned

- Building
	- `ClusterMaster.handle_result_reported_from_slave()`
	- Build has all the slaves it needs, slaves are reporting results back and getting new subjobs
	- Again, canceling during this phase has the worst behavior. Because of the line I mentioned above in ClusterMaster (`if not build.is_finished or build.has_error:`), the master *does nothing* in response to receiving a subjob result for a canceled build. This means the slave will be waiting forever for the master to send it more work for the build.
		- This issue could be partially due to fragility in the design. Should slaves be fetching subjobs from the master instead of the master sending subjobs to slaves?

- Executing post-build tasks
	- `Build._mark_subjob_complete()` -> `self.finish()` -> `Build._perform_async_postbuild_tasks()`
	- All subjobs for the buld have finished and the master is creating the build result archive.
	- The BuildFSM is still in the BUILDING state while postbuild tasks are executing, so CANCEL is a valid transition. Right now if a build is canceled while postbuild tasks are executing it will enter the CANCELED state, even though everything will still finish normally. (Postbuild tasks will not be stopped even if the build enters CANCELED state.)
	- If a build is canceled in this state do we want to actually cancel it or just let it finish?
	- This is probably fine for now but we may want to revisit. 

### Major tasks
These are the first major tasks I think we should take towards fixing build cancellation:
1. Fix cancellation for `BUILDING` builds.
	- Right now if a build is canceled while building, any slave working on the build will get stuck forever.
	- The if-statement in `ClusterMaster.handle_result_reported_from_slave()` I mentioned above will cause slaves to get stuck if a build is canceled while building.

2. Fix cancellaton for builds canceled before or during atomizing. (#224)
	- Right now the build is eventually put into the `ERROR` state, and the entire build executes normally (nothing is canceled).
	- The build should not go into the `ERROR` state; it should stay in the `CANCELED` state.
	- Two potential places we should be checking for `CANCELED` state:
		- `BuildRequestHandler._prepare_build_async()` (after `build.prepare()`)
		- `build_scheduler.needs_more_slaves()` <-- this one probably more important

3. Don't do atomization if build has already been canceled.
	- Probably just need an extra check in `BuildRequestHandler._prepare_build_async()` before calling `build.prepare()`.
	- Alternatively, see [the note in `build.prepare()`](https://github.com/box/ClusterRunner/blob/master@%7B2017-08-01%7D/app/master/build.py#L150-L151) about moving logic into a state machine callback. That could be a cleaner approach.

**Comment by cmcginty** [comment]
See also PE-13362

**Comment by shriganeshs** [comment]
I think this is fixed now (#405 #407 #399).

**Comment by josephharrington** [comment]
🎆🍾🙌💯🥇👍😹👑

**Comment by tjlee0909** [comment]
I had sensed an awakening in the force. It was this bug closing.
