### ISSUE TITLE
Redis vs SQLite Benchmarks

### ISSUE THREAD

**Issue by nickzuber** [box/ClusterRunner#400]
Overview
---------

I created an ran a few benchmarks to get an idea of how Redis and SQLite perform in mock situations that could appear in cluster runner for storing and retrieving builds. 

The simulations might not be totally accurate, so if anyone has any better ideas for how we can simulate situations better feel free to leave some feedback. Here are how I did the following tests:

Insertion
---------

For `n` amount of mock builds, we serialize the data as a string using `json.dumps` and then insert it into either an SQLite table or into a persisted Redis db.

#### SQLite
```python
sqlite_connection.execute('INSERT INTO test VALUES(?, ?)', (key, json.dumps(data[key])))
``` 
#### Redis 
```python
redis_connection.set(key, json.dumps(data[key]))
``` 

Accessing
---------

For `n` amount of mock build ids, we get query for that build id and receive the build, then we deserialize the build back into an object.

#### SQLite
```python
sqlite_connection.execute('SELECT * FROM test WHERE key=?', (key,))
build_id, build = sqlite_connection.fetchone()
build = json.loads(build)
``` 
#### Redis 
```python
json.loads(redis_connection.get(key).decode('utf-8'))
``` 

Results (with serialization & deserialization)
-------

#### 1,000 builds

&nbsp; | SQLite | Redis
--- | --- | ---
**insert** | 0.02 sec | 0.09 sec
**access** | 0.11 sec | 0.09 sec

#### 5,000 builds

&nbsp; | SQLite | Redis
--- | --- | ---
**insert** | 0.08 sec | 0.40 sec
**access** | 2.07 sec | 0.38 sec

#### 10,000 builds

&nbsp; | SQLite | Redis
--- | --- | ---
**insert** | 0.18 sec | 0.78 sec
**access** | 9.09 sec | 0.72 sec

#### 20,000 builds

&nbsp; | SQLite | Redis
--- | --- | ---
**insert** | 0.32 sec | 1.57 sec
**access** | 67.49 sec | 1.43 sec

Results (**without** serialization & deserialization)
-------

#### 1,000 builds

&nbsp; | SQLite | Redis
--- | --- | ---
**insert** | 0.00 sec | 0.06 sec
**access** | 0.05 sec | 0.06 sec

#### 5,000 builds

&nbsp; | SQLite | Redis
--- | --- | ---
**insert** | 0.01 sec | 0.30 sec
**access** | 1.08 sec | 0.28 sec

#### 10,000 builds

&nbsp; | SQLite | Redis
--- | --- | ---
**insert** | 0.20 sec | 0.60 sec
**access** | 4.70 sec | 0.56 sec

#### 20,000 builds

&nbsp; | SQLite | Redis
--- | --- | ---
**insert** | 0.40 sec | 1.18 sec
**access** | 15.73 sec | 1.20 sec

## Thoughts

Here is a copy of the [code which I used to collect these benchmarks](https://gist.github.com/nickzuber/d6571dd6c630ece6b9745c0e944e3d39), if you notice any flaws or want to suggest improvements to increase accuracy, please leave some feedback.

## Important Note

This test was done using manual build ids as keys to query by. SQLite provides an internal, auto-incrementing key called `ROWID` that starts at 1 and continues to increment itself as more rows get inserted into the table. We could use this `ROWID` as build ids since they both have the same behavior we desire, and using `ROWID` is incredibly performant and doesn't get affected by deleting rows.

[Results using ROWID (**without** serialization & deserialization)](#rowid)
--

#### 20,000 builds

&nbsp; | SQLite | Redis
--- | --- | ---
**insert** | 0.03 sec | 1.18 sec
**access** | 0.29 sec | 1.20 sec

**Comment by josephharrington** [comment]
See also #406.
