### ISSUE TITLE
Build will hang forever if an allocated slave dies

### ISSUE THREAD

**Issue by josephharrington** [box/ClusterRunner#65]
Right now if a command in setup_build hangs or fails on a single slave, then the entire build will hang even if all subjobs complete on other slaves.

The reason is that we have some code that blocks a build from finishing until no slaves report as working on that build.

**Comment by wjdhollow** [comment]
This also happens during teardown

**Comment by wjdhollow** [comment]
Just verified it also happens if a slave dies while working on a subjob.
